#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start-up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, it is
#       recommended to use that to run this script.
#
#   (2) The Java virtual machine's startup-up script requires a proper -X vm option
#       passed in as the first or an early argument in the command line.
#
#       Without this, the JVM defaults will be used. The defaults usually use too
#       little heap and too little stack and insufficient number of file handles,
#       so the application may crash with a StackOverflowError or an OutOfMemoryError.
#
#       For optimal performance, the variables below (based on experience empirically
#       tested) should always be set.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$( ls -ld "$PRG" | sed 's/.*-> //' )
    case $link in
      /*)
        PRG=$link
        ;;
      *)
        PRG=$( cd "$( dirname "$PRG" )" && pwd -P )
        PRG="$PRG/$link"
        ;;
    esac
done

SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_JAR="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"
CLASSPATH=$APP_JAR

# Start the Gradle daemon off with reasonable defaults for heapsize.
# 2GB should be enough for most projects, increase heap size if you have modules or multi-module projects
# HOST_MOD depends on the required memory.
DEFAULT_JVM_OPTS=" -Xmx2g -XX:MaxMetaspaceSize=512m"

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$msys" = "false" ] ; then
    MAX_FD_LIMIT=$( ulimit -H -n )
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD_LIMIT" != "unlimited" ] ; then
            ulimit -n $MAX_FD_LIMIT
        fi
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in
              -*)   false ;;
              /?*)
                arg=$( cygpath --path --windows "$arg" )
                ;;
              *)    false ;;
            esac
        then
            arg=$( printf '%s\n' "$arg" | sed "s/'/'\\\\''/g" )
            APP_ARGS=$APP_ARGS" '$arg'"
        else
            APP_ARGS=$APP_ARGS" $arg"
        fi
    done
fi

# Split up the JVM_OPTS And APP_ARGS to let people use double-quoted strings
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

trap "stty echo; exit" INT TERM
java "$@"
