name: Android CI/APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # GitHub-ன் அதிகாரப்பூர்வ பில்டர் கருவியைப் பயன்படுத்துகிறோம்
    # இது எல்லா ஃபோல்டர்களையும் செக் செய்து தானாகவே பில்ட் செய்யும்
    - name: Build with Gradle Action
      uses: gradle/gradle-build-action@v3
      with:
        arguments: assembleDebug 
        # இதைக் கொடுத்தால் gradlew இல்லாமலேயே பில்ட் ஆகும்
        generate-job-summary: true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LyraSaver-APK
        path: "**/build/outputs/apk/debug/*.apk" # எல்லா ஃபோல்டரிலும் APK-வைத் தேடும்